/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.2 .\public\models\cypher.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'

const Cypher = (props) => {
  const { nodes, materials } = useGLTF('/models/cypher.glb')
  const refobj = useRef()

  return (
    <group {...props} dispose={null} ref={refobj}>
      <mesh geometry={nodes.Alpha_Board_v2_1.geometry} material={materials.PCB} />
      <mesh geometry={nodes.Alpha_Board_v2_2.geometry} material={materials.Lead} />
      <mesh geometry={nodes.Alpha_Board_v2_3.geometry} material={materials.Color} />
      <mesh geometry={nodes.Alpha_Board_v2_4.geometry} material={materials.Color} />
      <mesh geometry={nodes.Alpha_Board_v2_5.geometry} material={materials.Markers} position={[0, 0.001, 0]}/>
      <mesh geometry={nodes.Alpha_Board_v2_6.geometry} material={materials.Ceramic} />
      <mesh geometry={nodes.Alpha_Board_v2_7.geometry} material={materials.Ceramic} />
      <mesh geometry={nodes.Alpha_Board_v2_8.geometry} material={materials.Markers} position={[0, 0.001, 0]}/>
      <mesh geometry={nodes.Alpha_Board_v2_9.geometry} material={materials.Lead} />
      <mesh geometry={nodes.Alpha_Board_v2_10.geometry} material={materials.Aluminum} />
      <mesh geometry={nodes.Alpha_Board_v2_11.geometry} material={materials.Lead} />
      <mesh geometry={nodes.Alpha_Board_v2_12.geometry} material={materials.Markers} position={[0, 0.001, 0]}/>
      <mesh geometry={nodes.Alpha_Board_v2_13.geometry} material={materials.Ceramic} />
      <mesh geometry={nodes.Alpha_Board_v2_14.geometry} material={materials.Markers} position={[0, 0.001, 0]}/>
      <mesh geometry={nodes.Alpha_Board_v2_15.geometry} material={materials.Lead} />
      <mesh geometry={nodes.Alpha_Board_v2_16.geometry} material={materials.Ceramic} />
      <mesh geometry={nodes.Alpha_Board_v2_17.geometry} material={materials.Aluminum} />
      <mesh geometry={nodes.Alpha_Board_v2_18.geometry} material={materials.Aluminum} />
      <mesh geometry={nodes.Alpha_Board_v2_19.geometry} material={materials.Aluminum} />
      <mesh geometry={nodes.Alpha_Board_v2_20.geometry} material={materials.Aluminum} />
      <mesh geometry={nodes.Alpha_Board_v2_21.geometry} material={materials.Lead} />
      <mesh geometry={nodes.Alpha_Board_v2_22.geometry} material={materials.Aluminum} />
      <mesh geometry={nodes.Alpha_Board_v2_23.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.Alpha_Board_v2_24.geometry} material={materials.Copper} />
      <mesh geometry={nodes.Alpha_Board_v2_25.geometry} material={materials.Aluminum} />
    </group>
  )
}

useGLTF.preload('/models/cypher.glb')

export default Cypher